# Generated by Django 5.1.3 on 2024-11-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_contacto', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('area_lote', models.FloatField(blank=True, null=True)),
                ('area_construida', models.FloatField(blank=True, null=True)),
                ('numero_habitaciones', models.SmallIntegerField(blank=True, null=True)),
                ('numero_banos', models.SmallIntegerField(blank=True, null=True)),
                ('numero_garaje', models.SmallIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('imagen_principal', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'propiedades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
